### ISSUE TITLE
初回起動時にポート番号を尋ねる

### ISSUE THREAD

**Issue by sakurapleasure** [Petitsurume/ayano#1]
+ config.tsのschemasに`name: "port"`である質問事項を追加
+ `type`は`number`でいいのか
+ ポート番号に規格外の文字を入力された際の処理を組む

**Comment by Petitsurume** [comment]
環境変数PORTを利用してください。
https://github.com/Petitsurume/ayano/blob/d4949c599069dec88ba4a82dd06d326610807422/src/main.ts#L21
